import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/PageHeader";
import { Sparkles, AlertTriangle, Send, Loader2, Square, RotateCcw } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { useChat } from "@ai-sdk/react";
import type { UIMessage } from "ai";
import { createAuthedChatTransport } from "@/lib/authed-chat-transport";

export const Route = createFileRoute("/symptom-checker")({ component: SymptomChecker });

const STARTERS = [
  "Adult with 3 days of dull morning headache and mild nausea — triage questions?",
  "Pediatric patient, fever 39.2°C for 48h, no rash — differentials to consider?",
  "Chest tightness on exertion, resolves with rest — red flags to screen?",
];

function messageText(m: UIMessage) {
  return m.parts
    .map((p) => (p.type === "text" ? p.text : ""))
    .filter(Boolean)
    .join("\n");
}

function SymptomChecker() {
  const [input, setInput] = useState("");
  const scrollRef = useRef<HTMLDivElement>(null);
  const transport = useMemo(() => createAuthedChatTransport(), []);
  const { messages, sendMessage, status, stop, setMessages, error } = useChat({ transport });
  const isLoading = status === "submitted" || status === "streaming";

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight, behavior: "smooth" });
  }, [messages, status]);

  function submit(e?: FormEvent) {
    e?.preventDefault();
    const t = input.trim();
    if (!t || isLoading) return;
    sendMessage({ text: `Triage assistance request from clinician:\n${t}` });
    setInput("");
  }

  return (
    <div>
      <PageHeader
        eyebrow="Clinical decision support"
        title="AI Symptom Checker"
        description="Assistive triage to support — not replace — clinical judgment."
      />

      <div className="rounded-xl border border-warning/30 bg-warning/10 p-4 mb-5 flex items-start gap-3">
        <AlertTriangle className="size-5 text-warning shrink-0 mt-0.5" />
        <div className="text-sm">
          <div className="font-medium text-foreground">Assistive only · not a diagnosis</div>
          <div className="text-muted-foreground text-xs mt-0.5">
            Output is generated by an AI model. Always verify against patient history and your own clinical judgment. Not for autonomous use with patients.
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div className="lg:col-span-2 rounded-xl border border-border bg-card overflow-hidden flex flex-col" style={{ boxShadow: "var(--shadow-card)", minHeight: 520 }}>
          <div className="px-5 py-4 border-b border-border flex items-center justify-between gap-2">
            <div className="flex items-center gap-2">
              <div className="size-8 rounded-lg flex items-center justify-center text-primary-foreground" style={{ background: "var(--gradient-primary)" }}>
                <Sparkles className="size-4" />
              </div>
              <div>
                <div className="font-semibold tracking-tight text-sm">Triage Assistant</div>
                <div className="text-[11px] text-muted-foreground">Staff-only · powered by HealthOS Copilot</div>
              </div>
            </div>
            {messages.length > 0 && (
              <button
                onClick={() => setMessages([])}
                className="text-xs text-muted-foreground hover:text-foreground inline-flex items-center gap-1"
              >
                <RotateCcw className="size-3" /> New session
              </button>
            )}
          </div>

          <div ref={scrollRef} className="flex-1 p-5 space-y-4 overflow-auto">
            {messages.length === 0 && !isLoading && (
              <div className="h-full flex flex-col items-center justify-center text-center gap-3 py-10">
                <div className="text-sm text-muted-foreground max-w-sm">
                  Describe the presentation — symptoms, duration, vitals — and the assistant will suggest triage questions and differentials for clinician review.
                </div>
                <div className="flex flex-col gap-2 w-full max-w-md">
                  {STARTERS.map((s) => (
                    <button
                      key={s}
                      onClick={() => { sendMessage({ text: `Triage assistance request from clinician:\n${s}` }); }}
                      className="text-left text-xs px-3 py-2 rounded-lg border border-border hover:bg-secondary/60 transition"
                    >
                      {s}
                    </button>
                  ))}
                </div>
              </div>
            )}

            {messages.map((m) => (
              <div key={m.id} className={`flex ${m.role === "user" ? "justify-end" : "justify-start"}`}>
                <div className={`max-w-[80%] rounded-2xl px-4 py-2.5 text-sm whitespace-pre-line ${
                  m.role === "user" ? "bg-primary text-primary-foreground rounded-br-sm" : "bg-secondary text-foreground rounded-bl-sm"
                }`}>
                  {messageText(m)}
                </div>
              </div>
            ))}

            {status === "submitted" && (
              <div className="flex justify-start">
                <div className="rounded-2xl px-4 py-2.5 bg-secondary text-sm text-muted-foreground inline-flex items-center gap-2">
                  <Loader2 className="size-3.5 animate-spin" /> Thinking…
                </div>
              </div>
            )}

            {error && (
              <div className="rounded-lg border border-destructive/30 bg-destructive/5 px-3 py-2 text-xs text-destructive flex items-center justify-between gap-2">
                <span>The assistant is unavailable right now — {error.message || "request failed"}.</span>
                <button onClick={() => submit()} className="underline shrink-0">Retry</button>
              </div>
            )}
          </div>

          <form onSubmit={submit} className="p-3 border-t border-border flex items-center gap-2">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Describe symptoms, duration, vitals…"
              aria-label="Describe symptoms"
              className="flex-1 h-10 px-3 rounded-lg bg-secondary text-sm outline-none focus:ring-2 focus:ring-ring/40"
            />
            {isLoading ? (
              <button type="button" onClick={() => stop()} aria-label="Stop generating" className="h-10 w-10 rounded-lg flex items-center justify-center bg-secondary text-foreground">
                <Square className="size-4" />
              </button>
            ) : (
              <button type="submit" disabled={!input.trim()} aria-label="Send" className="h-10 w-10 rounded-lg flex items-center justify-center text-primary-foreground disabled:opacity-50" style={{ background: "var(--gradient-primary)" }}>
                <Send className="size-4" />
              </button>
            )}
          </form>
        </div>

        <div className="space-y-4">
          <div className="rounded-xl border border-border bg-card p-5" style={{ boxShadow: "var(--shadow-card)" }}>
            <div className="font-semibold tracking-tight text-sm mb-3">How to get good triage output</div>
            <ul className="space-y-2 text-xs text-muted-foreground list-disc pl-4">
              <li>Include age, duration, severity, and relevant vitals.</li>
              <li>Mention current medications and allergies.</li>
              <li>State what has already been ruled out.</li>
              <li>Ask for differentials, triage questions, or red-flag screens explicitly.</li>
            </ul>
          </div>
          <div className="rounded-xl border border-border bg-card p-5" style={{ boxShadow: "var(--shadow-card)" }}>
            <div className="font-semibold tracking-tight text-sm mb-2">Common red flags to screen</div>
            <div className="text-xs text-muted-foreground leading-relaxed">
              Sudden/thunderclap onset · vision changes · neck stiffness · focal neuro deficits · chest pain with exertion · trauma · immunocompromise · pregnancy. Always escalate per clinic protocol when present.
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
