import { createFileRoute } from "@tanstack/react-router";
import { PageHeader } from "@/components/PageHeader";
import { Sparkles, AlertTriangle, Send } from "lucide-react";
import { useState } from "react";

export const Route = createFileRoute("/symptom-checker")({ component: SymptomChecker });

const sampleConversation = [
  { role: "patient", text: "I've had a dull headache for 3 days, worse in the morning, with mild nausea." },
  { role: "ai", text: "Thanks. A few quick questions: any vision changes, neck stiffness, or recent head injury? Also, current medications?" },
  { role: "patient", text: "No vision changes, no injury. Taking lisinopril daily." },
  { role: "ai", text: "Most likely differentials based on report: tension-type headache, medication-related, or sinus involvement. Red flags absent. Suggested for clinician review: BP check, hydration assessment, consider trial of analgesic if appropriate.\n\nThis is decision support only — not a diagnosis." },
];

function SymptomChecker() {
  const [input, setInput] = useState("");

  return (
    <div>
      <PageHeader
        eyebrow="Clinical decision support"
        title="AI Symptom Checker"
        description="Assistive triage to support — not replace — clinical judgment."
      />

      <div className="rounded-xl border border-warning/30 bg-warning/10 p-4 mb-5 flex items-start gap-3">
        <AlertTriangle className="size-5 text-warning shrink-0 mt-0.5" />
        <div className="text-sm">
          <div className="font-medium text-foreground">Assistive only · not a diagnosis</div>
          <div className="text-muted-foreground text-xs mt-0.5">
            Output is generated by an AI model. Always verify against patient history and your own clinical judgment. Not for autonomous use with patients.
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div className="lg:col-span-2 rounded-xl border border-border bg-card overflow-hidden flex flex-col" style={{ boxShadow: "var(--shadow-card)", minHeight: 520 }}>
          <div className="px-5 py-4 border-b border-border flex items-center gap-2">
            <div className="size-8 rounded-lg flex items-center justify-center text-primary-foreground" style={{ background: "var(--gradient-primary)" }}>
              <Sparkles className="size-4" />
            </div>
            <div>
              <div className="font-semibold tracking-tight text-sm">Triage Assistant</div>
              <div className="text-[11px] text-muted-foreground">Session for Maya Chen · 42F</div>
            </div>
          </div>
          <div className="flex-1 p-5 space-y-4 overflow-auto">
            {sampleConversation.map((m, i) => (
              <div key={i} className={`flex ${m.role === "patient" ? "justify-end" : "justify-start"}`}>
                <div className={`max-w-[80%] rounded-2xl px-4 py-2.5 text-sm whitespace-pre-line ${
                  m.role === "patient" ? "bg-primary text-primary-foreground rounded-br-sm" : "bg-secondary text-foreground rounded-bl-sm"
                }`}>
                  {m.text}
                </div>
              </div>
            ))}
          </div>
          <div className="p-3 border-t border-border flex items-center gap-2">
            <input
              value={input}
              onChange={(e) => setInput(e.target.value)}
              placeholder="Describe symptoms…"
              className="flex-1 h-10 px-3 rounded-lg bg-secondary text-sm outline-none focus:ring-2 focus:ring-ring/40"
            />
            <button className="h-10 w-10 rounded-lg flex items-center justify-center text-primary-foreground" style={{ background: "var(--gradient-primary)" }}>
              <Send className="size-4" />
            </button>
          </div>
        </div>

        <div className="space-y-4">
          <div className="rounded-xl border border-border bg-card p-5" style={{ boxShadow: "var(--shadow-card)" }}>
            <div className="font-semibold tracking-tight text-sm mb-3">Suggested differentials</div>
            <ul className="space-y-2 text-sm">
              {[
                ["Tension-type headache", "62%"],
                ["Medication side-effect", "21%"],
                ["Sinus involvement", "11%"],
                ["Other", "6%"],
              ].map(([label, pct]) => (
                <li key={label} className="flex items-center justify-between">
                  <span>{label}</span>
                  <span className="text-xs text-muted-foreground tabular-nums">{pct}</span>
                </li>
              ))}
            </ul>
          </div>
          <div className="rounded-xl border border-border bg-card p-5" style={{ boxShadow: "var(--shadow-card)" }}>
            <div className="font-semibold tracking-tight text-sm mb-2">Red-flag screen</div>
            <div className="text-xs text-success font-medium">No red flags detected.</div>
            <div className="text-xs text-muted-foreground mt-2">Vision changes · neck stiffness · trauma · thunderclap onset</div>
          </div>
        </div>
      </div>
    </div>
  );
}