/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TelemedicineIndexRouteImport } from './routes/telemedicine.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as TelemedicineAppointmentIdRouteImport } from './routes/telemedicine.$appointmentId'
import { Route as SettingsOrganizationRouteImport } from './routes/settings.organization'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalPrescriptionsRouteImport } from './routes/portal.prescriptions'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalLabsRouteImport } from './routes/portal.labs'
import { Route as PortalBillingRouteImport } from './routes/portal.billing'
import { Route as PortalAppointmentsRouteImport } from './routes/portal.appointments'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as BillingInvoiceIdRouteImport } from './routes/billing.$invoiceId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineIndexRoute = TelemedicineIndexRouteImport.update({
  id: '/telemedicine/',
  path: '/telemedicine/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineAppointmentIdRoute =
  TelemedicineAppointmentIdRouteImport.update({
    id: '/telemedicine/$appointmentId',
    path: '/telemedicine/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsOrganizationRoute = SettingsOrganizationRouteImport.update({
  id: '/settings/organization',
  path: '/settings/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPrescriptionsRoute = PortalPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLabsRoute = PortalLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBillingRoute = PortalBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAppointmentsRoute = PortalAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PortalRoute,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingInvoiceIdRoute = BillingInvoiceIdRouteImport.update({
  id: '/$invoiceId',
  path: '/$invoiceId',
  getParentRoute: () => BillingRoute,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRouteWithChildren
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/mcp': typeof McpRoute
  '/portal': typeof PortalRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/billing/$invoiceId': typeof BillingInvoiceIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/patients/': typeof PatientsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/telemedicine/': typeof TelemedicineIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRouteWithChildren
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/mcp': typeof McpRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/billing/$invoiceId': typeof BillingInvoiceIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/patients': typeof PatientsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/telemedicine': typeof TelemedicineIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/billing': typeof BillingRouteWithChildren
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/mcp': typeof McpRoute
  '/portal': typeof PortalRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/billing/$invoiceId': typeof BillingInvoiceIdRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/billing': typeof PortalBillingRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/organization': typeof SettingsOrganizationRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/patients/': typeof PatientsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/telemedicine/': typeof TelemedicineIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/mcp'
    | '/portal'
    | '/prescriptions'
    | '/symptom-checker'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/schedules'
    | '/admin/users'
    | '/api/chat'
    | '/billing/$invoiceId'
    | '/patients/$patientId'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/labs'
    | '/portal/messages'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/settings/organization'
    | '/telemedicine/$appointmentId'
    | '/patients/'
    | '/portal/'
    | '/telemedicine/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/mcp'
    | '/prescriptions'
    | '/symptom-checker'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/schedules'
    | '/admin/users'
    | '/api/chat'
    | '/billing/$invoiceId'
    | '/patients/$patientId'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/labs'
    | '/portal/messages'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/settings/organization'
    | '/telemedicine/$appointmentId'
    | '/patients'
    | '/portal'
    | '/telemedicine'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/appointments'
    | '/billing'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/mcp'
    | '/portal'
    | '/prescriptions'
    | '/symptom-checker'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/schedules'
    | '/admin/users'
    | '/api/chat'
    | '/billing/$invoiceId'
    | '/patients/$patientId'
    | '/portal/appointments'
    | '/portal/billing'
    | '/portal/labs'
    | '/portal/messages'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/settings/organization'
    | '/telemedicine/$appointmentId'
    | '/patients/'
    | '/portal/'
    | '/telemedicine/'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BillingRoute: typeof BillingRouteWithChildren
  ClaimsRoute: typeof ClaimsRoute
  ComplianceRoute: typeof ComplianceRoute
  LabsRoute: typeof LabsRoute
  McpRoute: typeof McpRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrescriptionsRoute: typeof PrescriptionsRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiChatRoute: typeof ApiChatRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  SettingsOrganizationRoute: typeof SettingsOrganizationRoute
  TelemedicineAppointmentIdRoute: typeof TelemedicineAppointmentIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  TelemedicineIndexRoute: typeof TelemedicineIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine/': {
      id: '/telemedicine/'
      path: '/telemedicine'
      fullPath: '/telemedicine/'
      preLoaderRoute: typeof TelemedicineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine/$appointmentId': {
      id: '/telemedicine/$appointmentId'
      path: '/telemedicine/$appointmentId'
      fullPath: '/telemedicine/$appointmentId'
      preLoaderRoute: typeof TelemedicineAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/organization': {
      id: '/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof SettingsOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/prescriptions': {
      id: '/portal/prescriptions'
      path: '/prescriptions'
      fullPath: '/portal/prescriptions'
      preLoaderRoute: typeof PortalPrescriptionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/labs': {
      id: '/portal/labs'
      path: '/labs'
      fullPath: '/portal/labs'
      preLoaderRoute: typeof PortalLabsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/billing': {
      id: '/portal/billing'
      path: '/billing'
      fullPath: '/portal/billing'
      preLoaderRoute: typeof PortalBillingRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/appointments': {
      id: '/portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalAppointmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/$invoiceId': {
      id: '/billing/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/billing/$invoiceId'
      preLoaderRoute: typeof BillingInvoiceIdRouteImport
      parentRoute: typeof BillingRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BillingRouteChildren {
  BillingInvoiceIdRoute: typeof BillingInvoiceIdRoute
}

const BillingRouteChildren: BillingRouteChildren = {
  BillingInvoiceIdRoute: BillingInvoiceIdRoute,
}

const BillingRouteWithChildren =
  BillingRoute._addFileChildren(BillingRouteChildren)

interface PortalRouteChildren {
  PortalAppointmentsRoute: typeof PortalAppointmentsRoute
  PortalBillingRoute: typeof PortalBillingRoute
  PortalLabsRoute: typeof PortalLabsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalPrescriptionsRoute: typeof PortalPrescriptionsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAppointmentsRoute: PortalAppointmentsRoute,
  PortalBillingRoute: PortalBillingRoute,
  PortalLabsRoute: PortalLabsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalPrescriptionsRoute: PortalPrescriptionsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  BillingRoute: BillingRouteWithChildren,
  ClaimsRoute: ClaimsRoute,
  ComplianceRoute: ComplianceRoute,
  LabsRoute: LabsRoute,
  McpRoute: McpRoute,
  PortalRoute: PortalRouteWithChildren,
  PrescriptionsRoute: PrescriptionsRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiChatRoute: ApiChatRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  SettingsOrganizationRoute: SettingsOrganizationRoute,
  TelemedicineAppointmentIdRoute: TelemedicineAppointmentIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  TelemedicineIndexRoute: TelemedicineIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
