/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TelemedicineIndexRouteImport } from './routes/telemedicine.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as BillingIndexRouteImport } from './routes/billing.index'
import { Route as TelemedicineAppointmentIdRouteImport } from './routes/telemedicine.$appointmentId'
import { Route as PortalProfileRouteImport } from './routes/portal.profile'
import { Route as PortalPrescriptionsRouteImport } from './routes/portal.prescriptions'
import { Route as PortalMessagesRouteImport } from './routes/portal.messages'
import { Route as PortalLabsRouteImport } from './routes/portal.labs'
import { Route as PortalAppointmentsRouteImport } from './routes/portal.appointments'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as BillingAnalyticsRouteImport } from './routes/billing.analytics'
import { Route as BillingInvoiceIdRouteImport } from './routes/billing.$invoiceId'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSchedulesRouteImport } from './routes/admin.schedules'

const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineIndexRoute = TelemedicineIndexRouteImport.update({
  id: '/telemedicine/',
  path: '/telemedicine/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingIndexRoute = BillingIndexRouteImport.update({
  id: '/billing/',
  path: '/billing/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineAppointmentIdRoute =
  TelemedicineAppointmentIdRouteImport.update({
    id: '/telemedicine/$appointmentId',
    path: '/telemedicine/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPrescriptionsRoute = PortalPrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLabsRoute = PortalLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAppointmentsRoute = PortalAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PortalRoute,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingAnalyticsRoute = BillingAnalyticsRouteImport.update({
  id: '/billing/analytics',
  path: '/billing/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingInvoiceIdRoute = BillingInvoiceIdRouteImport.update({
  id: '/billing/$invoiceId',
  path: '/billing/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchedulesRoute = AdminSchedulesRouteImport.update({
  id: '/admin/schedules',
  path: '/admin/schedules',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/portal': typeof PortalRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/billing/$invoiceId': typeof BillingInvoiceIdRoute
  '/billing/analytics': typeof BillingAnalyticsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/billing/': typeof BillingIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/telemedicine/': typeof TelemedicineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/billing/$invoiceId': typeof BillingInvoiceIdRoute
  '/billing/analytics': typeof BillingAnalyticsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/billing': typeof BillingIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/portal': typeof PortalIndexRoute
  '/telemedicine': typeof TelemedicineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/portal': typeof PortalRouteWithChildren
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/admin/schedules': typeof AdminSchedulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/billing/$invoiceId': typeof BillingInvoiceIdRoute
  '/billing/analytics': typeof BillingAnalyticsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/labs': typeof PortalLabsRoute
  '/portal/messages': typeof PortalMessagesRoute
  '/portal/prescriptions': typeof PortalPrescriptionsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/billing/': typeof BillingIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/telemedicine/': typeof TelemedicineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/portal'
    | '/prescriptions'
    | '/symptom-checker'
    | '/admin/schedules'
    | '/admin/users'
    | '/api/chat'
    | '/billing/$invoiceId'
    | '/billing/analytics'
    | '/patients/$patientId'
    | '/portal/appointments'
    | '/portal/labs'
    | '/portal/messages'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/telemedicine/$appointmentId'
    | '/billing/'
    | '/patients/'
    | '/portal/'
    | '/telemedicine/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/prescriptions'
    | '/symptom-checker'
    | '/admin/schedules'
    | '/admin/users'
    | '/api/chat'
    | '/billing/$invoiceId'
    | '/billing/analytics'
    | '/patients/$patientId'
    | '/portal/appointments'
    | '/portal/labs'
    | '/portal/messages'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/telemedicine/$appointmentId'
    | '/billing'
    | '/patients'
    | '/portal'
    | '/telemedicine'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/appointments'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/portal'
    | '/prescriptions'
    | '/symptom-checker'
    | '/admin/schedules'
    | '/admin/users'
    | '/api/chat'
    | '/billing/$invoiceId'
    | '/billing/analytics'
    | '/patients/$patientId'
    | '/portal/appointments'
    | '/portal/labs'
    | '/portal/messages'
    | '/portal/prescriptions'
    | '/portal/profile'
    | '/telemedicine/$appointmentId'
    | '/billing/'
    | '/patients/'
    | '/portal/'
    | '/telemedicine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ClaimsRoute: typeof ClaimsRoute
  ComplianceRoute: typeof ComplianceRoute
  LabsRoute: typeof LabsRoute
  PortalRoute: typeof PortalRouteWithChildren
  PrescriptionsRoute: typeof PrescriptionsRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
  AdminSchedulesRoute: typeof AdminSchedulesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiChatRoute: typeof ApiChatRoute
  BillingInvoiceIdRoute: typeof BillingInvoiceIdRoute
  BillingAnalyticsRoute: typeof BillingAnalyticsRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  TelemedicineAppointmentIdRoute: typeof TelemedicineAppointmentIdRoute
  BillingIndexRoute: typeof BillingIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  TelemedicineIndexRoute: typeof TelemedicineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine/': {
      id: '/telemedicine/'
      path: '/telemedicine'
      fullPath: '/telemedicine/'
      preLoaderRoute: typeof TelemedicineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/': {
      id: '/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof BillingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine/$appointmentId': {
      id: '/telemedicine/$appointmentId'
      path: '/telemedicine/$appointmentId'
      fullPath: '/telemedicine/$appointmentId'
      preLoaderRoute: typeof TelemedicineAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/prescriptions': {
      id: '/portal/prescriptions'
      path: '/prescriptions'
      fullPath: '/portal/prescriptions'
      preLoaderRoute: typeof PortalPrescriptionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/messages': {
      id: '/portal/messages'
      path: '/messages'
      fullPath: '/portal/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/labs': {
      id: '/portal/labs'
      path: '/labs'
      fullPath: '/portal/labs'
      preLoaderRoute: typeof PortalLabsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/appointments': {
      id: '/portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalAppointmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/analytics': {
      id: '/billing/analytics'
      path: '/billing/analytics'
      fullPath: '/billing/analytics'
      preLoaderRoute: typeof BillingAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/$invoiceId': {
      id: '/billing/$invoiceId'
      path: '/billing/$invoiceId'
      fullPath: '/billing/$invoiceId'
      preLoaderRoute: typeof BillingInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schedules': {
      id: '/admin/schedules'
      path: '/admin/schedules'
      fullPath: '/admin/schedules'
      preLoaderRoute: typeof AdminSchedulesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalRouteChildren {
  PortalAppointmentsRoute: typeof PortalAppointmentsRoute
  PortalLabsRoute: typeof PortalLabsRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalPrescriptionsRoute: typeof PortalPrescriptionsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAppointmentsRoute: PortalAppointmentsRoute,
  PortalLabsRoute: PortalLabsRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalPrescriptionsRoute: PortalPrescriptionsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  ClaimsRoute: ClaimsRoute,
  ComplianceRoute: ComplianceRoute,
  LabsRoute: LabsRoute,
  PortalRoute: PortalRouteWithChildren,
  PrescriptionsRoute: PrescriptionsRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
  AdminSchedulesRoute: AdminSchedulesRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiChatRoute: ApiChatRoute,
  BillingInvoiceIdRoute: BillingInvoiceIdRoute,
  BillingAnalyticsRoute: BillingAnalyticsRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  TelemedicineAppointmentIdRoute: TelemedicineAppointmentIdRoute,
  BillingIndexRoute: BillingIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  TelemedicineIndexRoute: TelemedicineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
