/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'
import { Route as PrescriptionsRouteImport } from './routes/prescriptions'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TelemedicineIndexRouteImport } from './routes/telemedicine.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as TelemedicineAppointmentIdRouteImport } from './routes/telemedicine.$appointmentId'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const PrescriptionsRoute = PrescriptionsRouteImport.update({
  id: '/prescriptions',
  path: '/prescriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineIndexRoute = TelemedicineIndexRouteImport.update({
  id: '/telemedicine/',
  path: '/telemedicine/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemedicineAppointmentIdRoute =
  TelemedicineAppointmentIdRouteImport.update({
    id: '/telemedicine/$appointmentId',
    path: '/telemedicine/$appointmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/api/chat': typeof ApiChatRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/patients/': typeof PatientsIndexRoute
  '/telemedicine/': typeof TelemedicineIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/api/chat': typeof ApiChatRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/patients': typeof PatientsIndexRoute
  '/telemedicine': typeof TelemedicineIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/appointments': typeof AppointmentsRoute
  '/claims': typeof ClaimsRoute
  '/compliance': typeof ComplianceRoute
  '/labs': typeof LabsRoute
  '/prescriptions': typeof PrescriptionsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/api/chat': typeof ApiChatRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/telemedicine/$appointmentId': typeof TelemedicineAppointmentIdRoute
  '/patients/': typeof PatientsIndexRoute
  '/telemedicine/': typeof TelemedicineIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/prescriptions'
    | '/symptom-checker'
    | '/api/chat'
    | '/patients/$patientId'
    | '/telemedicine/$appointmentId'
    | '/patients/'
    | '/telemedicine/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/appointments'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/prescriptions'
    | '/symptom-checker'
    | '/api/chat'
    | '/patients/$patientId'
    | '/telemedicine/$appointmentId'
    | '/patients'
    | '/telemedicine'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/appointments'
    | '/claims'
    | '/compliance'
    | '/labs'
    | '/prescriptions'
    | '/symptom-checker'
    | '/api/chat'
    | '/patients/$patientId'
    | '/telemedicine/$appointmentId'
    | '/patients/'
    | '/telemedicine/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppointmentsRoute: typeof AppointmentsRoute
  ClaimsRoute: typeof ClaimsRoute
  ComplianceRoute: typeof ComplianceRoute
  LabsRoute: typeof LabsRoute
  PrescriptionsRoute: typeof PrescriptionsRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
  ApiChatRoute: typeof ApiChatRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  TelemedicineAppointmentIdRoute: typeof TelemedicineAppointmentIdRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  TelemedicineIndexRoute: typeof TelemedicineIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prescriptions': {
      id: '/prescriptions'
      path: '/prescriptions'
      fullPath: '/prescriptions'
      preLoaderRoute: typeof PrescriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine/': {
      id: '/telemedicine/'
      path: '/telemedicine'
      fullPath: '/telemedicine/'
      preLoaderRoute: typeof TelemedicineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemedicine/$appointmentId': {
      id: '/telemedicine/$appointmentId'
      path: '/telemedicine/$appointmentId'
      fullPath: '/telemedicine/$appointmentId'
      preLoaderRoute: typeof TelemedicineAppointmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppointmentsRoute: AppointmentsRoute,
  ClaimsRoute: ClaimsRoute,
  ComplianceRoute: ComplianceRoute,
  LabsRoute: LabsRoute,
  PrescriptionsRoute: PrescriptionsRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
  ApiChatRoute: ApiChatRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  TelemedicineAppointmentIdRoute: TelemedicineAppointmentIdRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  TelemedicineIndexRoute: TelemedicineIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
